//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace система_для_хранения_pdf_файлов.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Files
    {
        public int id_table_files { get; set; }
        public Nullable<int> id_Files { get; set; }
    
        public virtual Table_Image_Files Table_Image_Files { get; set; }
        public virtual Table_PDF_Files Table_PDF_Files { get; set; }
    }
}
