//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace система_для_хранения_pdf_файлов.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Image_Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table_Image_Files()
        {
            this.Table_Files = new HashSet<Table_Files>();
        }
    
        public int id_image { get; set; }
        public string name_image { get; set; }
        public string link_image_files { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Table_Files> Table_Files { get; set; }
    }
}
